### ISSUE TITLE
Unknown compression 2: blank image

### ISSUE THREAD

**Issue by BryanColle** [photopea/UTIF.js#107]
Hi!

Thanks for your library, it's great ❤️ 
I have an issue with a file I can't send to you for privacy reasons (it contains medical data from a customer). It's a tif file that opens fine in the preview app on Mac.

I looked at the logs and I saw a few things that might help you, including `Unknown compression 2`. I see that this is indeed not in the list of compressions the library supports. Is there any way this support could be added or is it impossible?

Here's everything I managed to gather from the logs, if something can help:

```
ext.js:7038 ==== 1606 157
ext.js:6939 Unknown compression 2
pp.js:505 Object {
  data: Uint8Array(460491) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...],
  height: 2291,
  isLE: true,
  t254: [0],
  t256: [1606],
  t257: [2291],
  t258: [1],
  t259: [2],
  t262: [0],
  t266: [1],
  t273: (15) [784, 3953, 13155, 20187, 27667, 33206, 40811, 46555, 48886, 51655, 52029, 52418, 52774, 53102, 53497],
  t274: [1],
  t277: [1],
  t278: [157],
  t279: (15) [3169, 9202, 7032, 7480, 5539, 7605, 5744, 2331, 2769, 374, 389, 356, 328, 395, 188],
  t282: Array(1)0: (2) [200, 1],
  t283: Array(1)0: (2) [200, 1],
  t296: [2],
  t305: ['Oi/GFS, writer v00.06.01P'],
  t32934: [0],
  width: 1606,
}
```

Thanks a lot!

**Comment by photopea** [comment]
Hi, I would need a TIFF file to fix it :( Could you maybe edit your TIFF in some program, remove sensitive data, and send it to me to support@photopea.com ?

**Comment by BryanColle** [comment]
Thanks for your reply!

I tried removing information from it, but then when I save it the compression changes (to one that is supported). I guess Preview.app only knows how to read the format, and not how to write it...

I will try to see if our customer can generate a white page from the same source so that there is no information on it. I will come back to you by Monday 👍

**Comment by BryanColle** [comment]
Mail sent with a "safe" file! Thanks again

**Comment by photopea** [comment]
I think I have fixed it. Could you check if you can open all your TIFF files at www.Photopea.com now?

**Comment by BryanColle** [comment]
Hi,

It appears to be working, awesome!

**Comment by zalolorza** [comment]
hi @photopea I'm seeing the same issue when using the UTIF npm package. Can you help me with the new fixed version? Many thanks!!

**Comment by BryanColle** [comment]
@zalolorza It only works on Photopea for now, it's not yet part of master here.
Also the npm package is not up to date at all, it appears to be 3 years behind.

**Comment by zalolorza** [comment]
Thanks @BryanColle . I saw that the npm package is behind and I downloaded this repo but the error is still there. Any idea when this will be implemented to UTIF on this repo @photopea? Thank you both :)

**Comment by photopea** [comment]
I just updated the latest UTIF.js here on Github :) thanks for helping me resolve this problem!
