### ISSUE TITLE
Lossless JPEG decoder broken for 16 bit diff values

### ISSUE THREAD

**Issue by SimonSegerblomRex** [photopea/UTIF.js#96]
Hi!

Your JPEG decoder is broken for 16 bit diff values, see [this](https://github.com/Beep6581/RawTherapee/pull/6190). It's a very easy fix, but I can't parse the minified code. I guess you will fix it by yourself based on the conversation with @thany in #89. (A workaround could be to replace your decoder with [this one](https://github.com/rii-mango/JPEGLosslessDecoderJS).)

**Comment by SimonSegerblomRex** [comment]
I can provide one tomorrow. (The decoder doesn't crash, the decoded image will just be corrupt. The results looks exactly the same in RawTherapee without the fix I linked to.)

**Comment by SimonSegerblomRex** [comment]
Here's a minimal DNG-file: [zeros-2x2-16bit.zip](https://github.com/photopea/UTIF.js/files/6277202/zeros-2x2-16bit.zip)

(The decoded image should be black (2x2 zeros).)

**Comment by SimonSegerblomRex** [comment]
Here's another example: [16bit-test.zip](https://github.com/photopea/UTIF.js/files/6277683/16bit-test.zip)

Expected output:
![expected](https://user-images.githubusercontent.com/8997425/114005549-ec609600-985f-11eb-8713-82794dcadf28.png)

Photopea:
![current](https://user-images.githubusercontent.com/8997425/114005532-e8cd0f00-985f-11eb-8e91-004875eb59c7.png)

**Comment by photopea** [comment]
I fixed it, an updated UTIF.js is here, and in Photopea.com :)

**Comment by SimonSegerblomRex** [comment]
> I fixed it, an updated UTIF.js is here, and in Photopea.com :)

Nice! Thanks for the fixing it so quickly 👍

**Comment by SimonSegerblomRex** [comment]
@photopea, I had a look at the [diff](https://github.com/photopea/UTIF.js/commit/8fc26cbe548079efc61297ac777bba765ea5205c#diff-aa0d4be33d6a5f7da30b7b6e46a90849c7db6a1c262821061b4811e6bb0d7b00) and now the `if(SSSS==16)return-32768` is in the right place (before erroneously decoding 16 bits), but it looks like you forgot to clean up the old faulty code in what used to be `function J` (now `function G`). You should change change this
`function G(w,J){var e=g(w,J);return w==16?-32768:o(e,w)}`
to
`function G(w,J){var e=g(w,J);return o(e,w)}`.

It doesn't affect the result, but I think you should fix it for readability. (I guess you are version controlling the original file in a private repository and that it's unnecessary to create a pull requst for this repository.)

**Comment by photopea** [comment]
Ok, it should be fixed now :) I wish I knew you before I started to write my own lossless JPG decoder, so that you could help me out :D

**Comment by SimonSegerblomRex** [comment]
> Ok, it should be fixed now :) I wish I knew you before I started to write my own lossless JPG decoder, so that you could help me out :D

Nice :) The [diff](https://github.com/photopea/UTIF.js/commit/b3d63ce4f24d5780945772143646a8c5b67f40e7#diff-aa0d4be33d6a5f7da30b7b6e46a90849c7db6a1c262821061b4811e6bb0d7b00) looks a bit strange though, maybe you added some other stuff by mistake?

**Comment by thany** [comment]
> A workaround could be to replace your decoder with [this one](https://github.com/rii-mango/JPEGLosslessDecoderJS).

This. Having minified code in a *source* repo is a bad idea for a plethora of reasons. I understand it's probably copyrighted code or something, but that just underlines the problem. Import it from the commercial package, don't copypaste it in.

If the source code was properly source, other folks could help improve the code. This can't ever happen with minified code. This should be the primary reason for allowing only sourcecode in the sourcecode.

**Comment by firetech** [comment]
> A workaround could be to replace your decoder with [this one](https://github.com/rii-mango/JPEGLosslessDecoderJS)

Quite easy to do:
```
UTIF.LosslessJpegDecode = function(buffer) {
  var decoder = new jpeg.lossless.Decoder();
  return decoder.decode(buffer);
};
```

(Doing this also solves #97, by the way.)
